### ISSUE TITLE
CollaboratorMethodNotFoundListener::getDoubledInterface() must be of the type string

### ISSUE THREAD

**Issue by duxet** [phpspec/phpspec#1147]
```
# php -v
PHP 7.1.8 (cli) (built: Aug  4 2017 18:55:44) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.8, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

# phpspec -v
phpspec 4.0.3
```

```
Uncaught TypeError: Argument 1 passed to PhpSpec\Listener\CollaboratorMethodNotFoundListener::getDoubledInterface() must be of the type string, object given, called in /var/www/project/vendor/phpspec/phpspec/src/PhpSpec/Listener/CollaboratorMethodNotFoundListener.php on line 99 and defined in /var/www/project/vendor/phpspec/phpspec/src/PhpSpec/Listener/CollaboratorMethodNotFoundListener.php:116
Stack trace:
#0 /var/www/project/vendor/phpspec/phpspec/src/PhpSpec/Listener/CollaboratorMethodNotFoundListener.php(99): PhpSpec\Listener\CollaboratorMethodNotFoundListener->getDoubledInterface(Object(Prophecy\Prophecy\ObjectProphecy))
#1 [internal function]: PhpSpec\Listener\CollaboratorMethodNotFoundListener->afterExample(Object(PhpSpec\Event\ExampleEvent), 'afterExample', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /var/www/project/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): call_user_func(Array, Object(PhpSpec\Event\ExampleEvent), 'afterExampl in /var/www/project/vendor/phpspec/phpspec/src/PhpSpec/Listener/CollaboratorMethodNotFoundListener.php on line 116
```

**Comment by avant1** [comment]
Could you please provide minimal reproducible scenario?

**Comment by arendjantetteroo** [comment]
In my case this happened because I referenced a method that did not exist yet in a function on a collaborator that was called by the spec. 

Hard to explain, will try to add a reproducible scenario.

**Comment by arendjantetteroo** [comment]
Reproducible scenario: https://github.com/arendjantetteroo/phpspec-issue-1147

It's clear this is a user error but the message does not help to understand what the problem is or where to find the issue.

**Comment by greg0ire** [comment]
Can you try https://github.com/phpspec/prophecy/pull/369 ?

**Comment by arendjantetteroo** [comment]
@greg0ire it does not change the output of the message. 369 is for the className while here it is a method that is missing.

**Comment by greg0ire** [comment]
Ok, thanks for trying anyway.

**Comment by arendjantetteroo** [comment]
Did something wrong with testing, that indeed fixes it for me.
