### ISSUE TITLE
Fatal error: Uncaught TypeError if phpspec.yml is empty

### ISSUE THREAD

**Issue by ThorstenS** [phpspec/phpspec#1172]
If the phpspec.yml file exists, but is empty, phpspec fails to run.

```
bin/phpspec run

Fatal error: Uncaught TypeError: Return value of PhpSpec\Console\Application::parseConfigFromExistingPath() must be of the type array, null returned in phpspec/phpspec/src/PhpSpec/Console/Application.php:248
Stack trace:
#0 phpspec/phpspec/src/PhpSpec/Console/Application.php(228): PhpSpec\Console\Application->parseConfigFromExistingPath('phpspec.yml')
#1 phpspec/phpspec/src/PhpSpec/Console/Application.php(216): PhpSpec\Console\Application->extractConfigFromFirstParsablePath(Array)
#2 phpspec/phpspec/src/PhpSpec/Console/Application.php(130): PhpSpec\Console\Application->parseConfigurationFile(Object(Symfony\Component\Console\Input\ArgvInput))
#3 phpspec/phpspec/src/PhpSpec/Console/Application.php(71): PhpSpec\Console\Application->loadConfigurationF in phpspec/phpspec/src/PhpSpec/Console/Application.php on line 248
```

**Comment by ciaranmcnulty** [comment]
Thanks for reporting!
