### ISSUE TITLE
Phar file broken

### ISSUE THREAD

**Issue by dmolineus** [phpspec/phpspec#1301]
I try to use the phpspec phar file (version 6.1.0 and 6.1.1). Seems like both are broken due to incompatibility with the uses symfony event dispatcher. Downgrade to older versions doesn't work as I already work on PHP 7.4.

```
$ php phpspec~6.1.1.phar run

✘ Fatal error happened while executing the following 
     
    Uncaught TypeError: Argument 2 passed to Symfony\Component\EventDispatcher\EventDispatcher::dispatch() must be an instance of Symfony\Component\EventDispatcher\Event or null, string given, called in phar:///.../phpspec~6.1.1.phar/src/PhpSpec/Util/DispatchTrait.php on line 22 and defined in phar:///.../phpspec~6.1.1.phar/vendor/symfony/event-dispatcher/EventDispatcher.php:37
Stack trace:
#0 phar:///.../phpspec~6.1.1.phar/src/PhpSpec/Util/DispatchTrait.php(22): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(PhpSpec\Event\SuiteEvent), 'beforeSuite')
#1 phar:///.../phpspec~6.1.1.phar/src/PhpSpec/Runner/SuiteRunner.php(52): PhpSpec\Runner\SuiteRunner->dispatch(Object(Symfony\Component\EventDispatcher\EventDispatcher), Object(PhpSpe in phar:///.../phpspec~6.1.1.phar/vendor/symfony/event-dispatcher/EventDispatcher.php on line 37 
```

**Comment by stof** [comment]
We might need to use php-scoper to rename vendor classes shipped in the phar, to avoid conflicts with the project code.

@dmolineus the workaround is to install phpspec with composer (in `require-dev`), so that Composer ensures you have compatible versions.

**Comment by dmolineus** [comment]
You're right, it's caused by confilicts with the project dependencies, so probably a duplicate of #1288.

**Comment by ciaranmcnulty** [comment]
I'll close as a duplicate then
